compile:
	@g++ src/*.cpp -I include -o build/AnalyseData.exe
	@./build/AnalyseData.exe

clean:
	@rm -f build/*
	@rm -f data/BestFit.txt
	@rm -f data/chi2.txt
	@rm -f data/x^y.txt
	@rm -f data/magnitudes.txt